### ISSUE TITLE
Add parserOptions { ecmaVersion: 5 }?

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/eslint-config-wikimedia#47]
Now we require ES5 parsing, should we add it to the preset?

**Comment by jdforrester** [comment]
@Krinkle in particular may have a view.

**Comment by Krinkle** [comment]
Seems fine. It's still relatively easy for individual projects to override back.

Note by the way that we aren't actually setting `ecmaVersion` right now. And it already defaults to 5 according to <http://eslint.org/docs/user-guide/configuring#specifying-parser-options>.

Changing ecmaVersion only influences the parser behaviour for very basic parse error exceptions (which hasn't changed much between ES3 and ES5 and we weren't even testing for unfortunately).

The real thing we should think about changing are the rules we configured _because_  of the previous requirement to support ES3. For example:
```json
    "dot-notation": [ "error", { "allowKeywords": false } ],
    "quote-props": [ "error", "as-needed", { "keywords": true } ],
```

.. and maybe a few others.

The good thing is that because these are not derived from `ecmaVersion`, we'll know exactly what we're changing and there shouldn't be any surprises. The down side is that when projects want to override to ES3 for one reason or another, they'll have to manually override each of these rules.

But.., I don't we should encourage that. Projects not yet ready to upgrade, simply shouldn't upgrade. There isn't any risk in continuing to use the current version for those projects. The eslint preset is versioned separately from ESLint itself, so they can still use the latest version of ESLint.

This configuration file is pure JSON with very little room for actual "bugs", so it's unlikely we'll ever need to provide any actual "support", if we want to. I'd propose the following:
* Make the default of `ecmaVersion: 5` explicit.
* Update es3-related rule configuration to newer patterns.
* Release as major version.

In the unlikely event someone finds a bug in the current version that affects ES3-only, we can always create a temporary `v0.x` branch based on the last version before the bump, and fix the bug there.

**Comment by jdforrester** [comment]
Done #53 for the first item. Let's ship in v0.4.0 for #50?

**Comment by edg2s** [comment]
See #57
