### ISSUE TITLE
Create a QUnit config

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-wikimedia#68]
We've started experimenting with [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) in VE. We should create a `wikimedia-qunit` ruleset (extending `wikimedia`) to hold our customisations.

At the moment it would be:
```json
{
	"extends": [
		"wikimedia",
		"plugin:qunit/recommended",
		"plugin:qunit/two"
	],
	"rules": {
		"qunit/no-assert-equal": "error",
		"qunit/no-early-return": "error",
		"qunit/no-negated-ok": "error",
		"qunit/require-expect": 0
	},
	"plugins": [ "qunit" ]
}
```

**Comment by jdforrester** [comment]
Or we could just merge it into `wikimedia`, which might be a bit aggressive?

**Comment by edg2s** [comment]
There were some issue with running QUnit tests on non-QUnit code (for example we had a local method named 'stop' which was false-positiving no-global-stop-start) - as well as being inefficient. We should keep the QUnit-extended ruleset separate so it can be run selectively on test files.

**Comment by Krinkle** [comment]
<https://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs>

We can have "wikimedia" and "wikimedia/qunit", distributed as part of the same package. Where the rules for QUnit would be in `/qunit.json`.

**Comment by edg2s** [comment]
Sounds good to me.

**Comment by Krinkle** [comment]
I wonder if the `eslint-plugin-qunit` dependency should or should not be included by eslint-config-wikimedia.

I think it'd be good to keep control over that dependency in the final repository, not here. On the other hand, we want to avoid weird run-time failures due to the final repo having a version we don't expect/support.

Perhaps a loose `peerDependencies` requirement would make sense? Similar to what karma-qunit does for qunit? E.g. we'd specify something like `"eslint-plugin-qunit": "^3.2.0"`.

**Comment by edg2s** [comment]
Can you prepare a patch with the data from my first comment? Sounds like you have a good idea of where it needs to go.
